# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - 'master'

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test

  cd: 
    needs: ci
    if: github.ref == 'refs/heads/master' #only run this job for master branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Tag
      id: tag
      uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: If no new tag, not deploying. Increment version in Package.json before merging or pushing to master
      if: steps.tag.outputs.tagname == 0
      run: exit 1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Build
      run: npm run build --if-present
    - name: Upload to s3 Bucket (tagged dir)
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: '.'
        destination_dir: ${{ steps.tag.outputs.tagname }}
    - name: Upload to s3 Bucket (latest dir)
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: '.'
        destination_dir: 'latest'  
    - uses: chrislennon/action-aws-cli@v1.1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - run: aws autoscaling start-instance-refresh --auto-scaling-group-name wipro-asg --strategy Rolling --preferences MinHealthyPercentage=50,InstanceWarmup=90
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        